openapi: 3.0.1
info:
  title: meta-validation-api
  description: APIs to validate XML metadata files based on the standard NAP-ISO19115:2003,
    the  Government of Canada-specific HNAP and the various business rules
  contact:
    name: Lu Bo
    email: bo.lu@canada.ca
  license:
    name: Apache Ant
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: "2021-03-03T20:25:33Z"
servers:
  - url: https://4nh2zjhata.execute-api.ca-central-1.amazonaws.com/Alpha3
  - url: http://4nh2zjhata.execute-api.ca-central-1.amazonaws.com/Alpha3
tags:
- name: XML Validator
  description: Everything about XML validation
  externalDocs:
    description: Find out more
    url: http://nrcan.canada.ca
paths:
  /validation:
    put:
      tags:
      - APIs
      summary: Update the master schematron file on the server
      description: ''
      requestBody:
        description: Schematron file that needs to be put/updated
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
        required: true
      responses:
        200:
          description: 'Schematron file updated successfully.'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Content-Type:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        402: 
          description: "Bad Request: Missing input file or input file does not seem to a schematron file. It should have *.sch or *.SCH file extension"
        404:
          description: "Bad Request: Error in the input data. The Content-Type should be mutipart/form-data."
        500:
          description: "Server (EC2) Instance is not running. Start the server and then run again."

    post:
      tags: 
      - APIs
      summary: 'XML file name that has to be validated by the schematron'
      description: ''
      requestBody:
        description: Name of the XML file that needs to be validated
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
        required: true
      responses:
        200:
          description: 'XML file will be validated with errors or issues, if there are any.'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Content-Type:
              description: "Response header type"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
        401:
          description: 'Bad Request: XML file to be validated is mising from the input data. You must provide an input xml file'
        402: 
          description: "Bad Request: Input file does not seem to a XML file. It should have *.xml or *.XML file extension"
        404:
          description: "Bad Request: Error in the input data. The Content-Type should be mutipart/form-data."
        500:
          description: "Server (EC2) Instance is not running. Start the server and then run again."
        
    #options:
    # summary: CORS support
    #  description: Enable CORS by returning correct headers
    #  tags:
    #  - APIs
    #  responses:
     #   "200":
      #    description: "200 response"
      #    headers:
      #      Access-Control-Allow-Origin:
      #        schema:
      #          type: "string"
      #      Access-Control-Allow-Methods:
      #        schema:
      #          type: "string"
      #      Access-Control-Allow-Headers:
      #        schema:
      #          type: "string"
      #    content:
      #      application/json:
      #        schema:
      #          $ref: "#/components/schemas/Empty"
    #x-amazon-apigateway-integration:
    #  type: mock
    #  requestTemplates:
    #    application/json: |
    #      {
    #        "statusCode" : 200
    #      }
    #  responses:
    #    default:
    #      statusCode: "200"
    #      responseParameters:
    #        method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
    #       method.response.header.Access-Control-Allow-Methods: '''*'''
    #        method.response.header.Access-Control-Allow-Origin: '''*'''
    #      responseTemplates:
    #        application/json: |
    #          {}
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"  

